version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5431:5432'
    volumes:
      - /var/folders/postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tabist
      PGDATA: /var/lib/postgresql/data/db-files/
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
